import { FaUser } from "react-icons/fa";
import "~/styles/globals.css";
import { type Metadata } from "next";
import { Geist } from "next/font/google";
import Carousel from "./_components/carousel"; 

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

function Topnav() {
  return (
    <nav className="flex items-center justify-between p-4 bg-auto text-white">
      <div className="flex-1"></div>
      
      <div className="flex justify-center flex-1">
        <img
          src="https://nqoiq4wi68.ufs.sh/f/2f9wccbRFAt91feVizjIsQmGHiBp0oa9WAXOtrNVzky62K8n"
          alt="Logo"
          className="h-15 w-40"
        />
      </div>
      <div className="flex-1 flex justify-end">
        <FaUser className="text-xl cursor-pointer text-white hover:text-gray-400 mr-5 transition-colors duration-200" /> 
      </div>
    </nav>
  );
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body style={{ display: 'flex', flexDirection: 'column', minHeight: '100vh' }}>
        <Topnav />
        <Carousel /> 
        <div style={{ flex: 1 }}>
          {children}
        </div> 
        {/* Footer lang ng text */}
        <footer style={{ textAlign: 'center', padding: '1rem', backgroundColor: '#0000' }}>
          <p>© AUTODEPOT PHILIPPINES CORPORATION. 2025 ALL RIGHTS RESERVED</p>
        </footer>
      </body>
    </html>
  );
}